version: "3.3"

services:

  openmrs-mysql:
    image: mysql:5.7
    container_name: openmrs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openmrs
    ports:
      - "3308:3306"
    volumes:
      - openmrs_mysql_data:/var/lib/mysql

  openmrs:
    image: openmrs/openmrs-reference-application-distro:2.12.0
    container_name: openmrs
    restart: always
    depends_on:
      - openmrs-mysql
    environment:
      DB_DATABASE: openmrs
      DB_HOST: openmrs-mysql
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_CREATE_TABLES: "true"
      DB_AUTO_UPDATE: "true"
    ports:
      - "8081:8080"

  mc_mysql:
    image: mysql:8.0
    container_name: mc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicconnect
      TZ: Asia/Kolkata
    ports:
      - "3307:3306"
    volumes:
      - mc_mysql_data:/var/lib/mysql

volumes:
  mc_mysql_data:
  openmrs_mysql_data:
